---
language: ruby
rvm:
- 2.1.5
matrix:
  allow-failures:
  - rvm: jruby
env:
  global:
  - secure: "Z9gYY+iN1CB6+6KOG9zhCFHqNoUpeDrO0asn6ocpsaAVpQ+5L1ehdLcneZR+c/8fEyplC1sPtPQaq3u1/xrZ8dluev6iRoDZvEAS3GDg594lIB9owBJXXQKKGddyKfdCcp6xcNphJtcgSNtuxfNmhQyTvSBp0TjBgVvknoa1dNE="
